version: "3.8"
name: dify  # 指定 Stack 名称，即项目名称，这里把静态服务器归为工具utils项目，不指定就是当前文件夹的名称
services:
  nginx:
    image: nginx
    container_name: nginx-server  # 指定容器名称，不指定就是（当前文件夹-image名称-序号）组成的名称
    restart: always
    ports:
      - "80:80"
      - "443:443" # 暴露 HTTPS 端口
      - "8000:80"
    volumes:
      - ../:/usr/share/nginx/html  # 静态服务根目录
#      - ./certs:/etc/nginx/certs  # SSL证书目录
#      - ./nginx.conf:/etc/nginx/nginx.conf  # nginx主配置文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # nginx主配置文件
      - ./mime.types:/etc/nginx/mime.types  # mime.types文件
#      - ./conf.d:/etc/nginx/conf.d  # 整个conf.d目录映射到容器/etc/nginx，加ro只读
#      - ./services:/etc/nginx/services  # 整个services目录映射到容器/etc/nginx，加ro只读
#      - ./sites-enabled:/etc/nginx/sites-enabled  # 整个sites-enabled目录映射到容器/etc/nginx，加ro只读
      # - ./html:/usr/share/nginx/html  # 根目录暂时不配在这里
#      - ./logs:/var/log/nginx

    # depends_on:  # 确保启动nginx前先启动ttsapi服务
      # - ttsapi
  
    dns:
      - 8.8.8.8
    networks:
      - dify
      
networks:
  dify:
    external: true